version: '3'

services:

  genoapp-front-static-prod:
    image: scilicium/geno_app-front:dev
    container_name: genoapp_front-static-prod
    labels:
      - traefik.enable=true
      - traefik.http.routers.genoapp-front-static-prod.entrypoints=websecure
      - traefik.http.routers.genoapp-front-static-prod.rule=Host(`genoapp.genouest.org`)
    networks:
      - web

networks:
  web:
    external: true
  genoapp:
    external: true
