version: '3'

services:

  genoapp-front-static-prod:
    image: scilicium/geno_app-front:uncover
    container_name: uncover
    ports:
      - "6548:80"
    networks:
      - web
      - genoapp

networks:
  web:
    external: true
  genoapp:
    external: true
