version: '3'

services:

  genoapp-front-static-prod:
    image: scilicium/geno_app-front:hudeca-viewer
    container_name: hudeca-viewer
    ports:
      - "80:80"
    networks:
      - web
      - genoapp

networks:
  web:
    external: true
  genoapp:
    external: true
