version: '3'

services:

  genoapp-front-static-prod:
    image: scilicium/geno_app-front:rgv-viewer
    container_name: rgv-viewer
    ports:
      - "6550:80"
    networks:
      - web
      - genoapp

networks:
  web:
    external: true
  genoapp:
    external: true
